import React, { useState, useEffect } from 'react';
import {
  X,
  Plus,
  DollarSign,
  Edit3,
  User,
  Calendar,
  CheckCircle,
  ChevronRight,
  Trash2
} from 'lucide-react';
import COLORS from '../../utils/colors';
import {
  get as getPracticeProfile,
  getFinancialTasks,
  getActiveFinancialTasks,
  updateFinancialTask,
  addFinancialTask,
  deleteFinancialTask
} from '../../storage/practiceProfileStorage';
import ConfirmDialog from './ConfirmDialog';

/**
 * FinancialTasksModal - Extracted from Dashboard.jsx
 * Modal for viewing and managing all financial tasks
 */
const FinancialTasksModal = ({ isOpen, onClose, onTasksChanged }) => {
  const [allFinancialTasks, setAllFinancialTasks] = useState([]);
  const [showAddFinancialTask, setShowAddFinancialTask] = useState(false);
  const [showCustomTaskForm, setShowCustomTaskForm] = useState(false);
  const [editingFinancialTask, setEditingFinancialTask] = useState(null);
  const [financialTaskForm, setFinancialTaskForm] = useState({
    title: '',
    description: '',
    category: 'reporting',
    priority: 'medium',
    assignedTo: '',
    dueDate: ''
  });
  const [confirmDialog, setConfirmDialog] = useState({ isOpen: false, type: null, taskId: null });

  // Load tasks on open
  useEffect(() => {
    if (isOpen) {
      setAllFinancialTasks(getFinancialTasks());
    }
  }, [isOpen]);

  // Get assignee list from practice profile
  const getAssigneeList = () => {
    const profile = getPracticeProfile();
    if (!profile) return [];

    const assignees = [];

    // Add GP partners
    if (profile.gps?.partners) {
      profile.gps.partners.forEach(p => {
        if (p.name) assignees.push({ name: p.name, role: 'Partner' });
      });
    }

    // Add salaried GPs
    if (profile.gps?.salaried) {
      profile.gps.salaried.forEach(g => {
        if (g.name) assignees.push({ name: g.name, role: 'Salaried GP' });
      });
    }

    // Add staff
    if (profile.staff) {
      profile.staff.forEach(s => {
        const name = s.name || `${s.firstName || ''} ${s.surname || ''}`.trim();
        if (name) assignees.push({ name, role: s.role || 'Staff' });
      });
    }

    // Add health check staff details if available
    if (profile.healthCheckData?.staffDetails) {
      profile.healthCheckData.staffDetails.forEach(s => {
        const name = `${s.firstName || ''} ${s.surname || ''}`.trim();
        if (name) {
          const role = s.staffType === 'nurse' ? 'Nurse' :
                       s.staffType === 'practiceManager' ? 'Practice Manager' :
                       s.staffType || 'Staff';
          assignees.push({ name, role });
        }
      });
    }

    return assignees;
  };

  // Create a new financial task
  const createFinancialTask = (taskData) => {
    return {
      id: `fin-task-${Date.now()}`,
      title: taskData.title,
      description: taskData.description || '',
      category: taskData.category || 'general',
      priority: taskData.priority || 'medium',
      status: 'pending',
      assignedTo: taskData.assignedTo || null,
      dueDate: taskData.dueDate || null,
      actionLink: taskData.actionLink || null,
      autoGenerated: taskData.autoGenerated || false,
      createdDate: new Date().toISOString(),
      notes: taskData.notes || ''
    };
  };

  // Handle adding a custom task
  const handleAddFinancialTask = () => {
    if (!financialTaskForm.title) return;

    const task = createFinancialTask({
      ...financialTaskForm,
      autoGenerated: false
    });

    addFinancialTask(task);
    setAllFinancialTasks(getFinancialTasks());
    setShowAddFinancialTask(false);
    setFinancialTaskForm({
      title: '',
      description: '',
      category: 'reporting',
      priority: 'medium',
      assignedTo: '',
      dueDate: ''
    });

    if (onTasksChanged) onTasksChanged();
  };

  // Handle editing a task
  const handleEditFinancialTask = (task) => {
    setEditingFinancialTask(task);
    setFinancialTaskForm({
      title: task.title || '',
      description: task.description || '',
      category: task.category || 'reporting',
      priority: task.priority || 'medium',
      assignedTo: task.assignedTo || '',
      dueDate: task.dueDate || '',
      status: task.status || 'pending'
    });
  };

  // Save task edit
  const handleSaveFinancialTaskEdit = () => {
    if (!editingFinancialTask) return;

    const updates = {
      title: financialTaskForm.title,
      description: financialTaskForm.description,
      category: financialTaskForm.category,
      priority: financialTaskForm.priority,
      assignedTo: financialTaskForm.assignedTo || null,
      dueDate: financialTaskForm.dueDate || null,
      status: financialTaskForm.status
    };

    if (financialTaskForm.status === 'completed' && editingFinancialTask.status !== 'completed') {
      updates.completedDate = new Date().toISOString();
    }

    updateFinancialTask(editingFinancialTask.id, updates);
    setAllFinancialTasks(getFinancialTasks());
    setEditingFinancialTask(null);
    setFinancialTaskForm({
      title: '',
      description: '',
      category: 'reporting',
      priority: 'medium',
      assignedTo: '',
      dueDate: ''
    });

    if (onTasksChanged) onTasksChanged();
  };

  // Quick status update (mark as complete) - show confirmation
  const handleQuickStatusUpdate = (taskId, newStatus) => {
    if (newStatus === 'completed') {
      setConfirmDialog({ isOpen: true, type: 'complete', taskId });
    } else {
      const updates = { status: newStatus };
      updateFinancialTask(taskId, updates);
      setAllFinancialTasks(getFinancialTasks());
      if (onTasksChanged) onTasksChanged();
    }
  };

  const handleConfirmComplete = () => {
    const updates = { status: 'completed', completedDate: new Date().toISOString() };
    updateFinancialTask(confirmDialog.taskId, updates);
    setAllFinancialTasks(getFinancialTasks());
    setConfirmDialog({ isOpen: false, type: null, taskId: null });
    if (onTasksChanged) onTasksChanged();
  };

  // Delete a task - show confirmation
  const handleDeleteFinancialTask = (taskId) => {
    setConfirmDialog({ isOpen: true, type: 'delete', taskId });
  };

  const handleConfirmDelete = () => {
    deleteFinancialTask(confirmDialog.taskId);
    setAllFinancialTasks(getFinancialTasks());
    setEditingFinancialTask(null);
    setConfirmDialog({ isOpen: false, type: null, taskId: null });
    if (onTasksChanged) onTasksChanged();
  };

  const handleCancelDialog = () => {
    setConfirmDialog({ isOpen: false, type: null, taskId: null });
  };

  if (!isOpen) return null;

  // Preset tasks for quick add
  const presetTasks = [
    { title: 'Run Profit & Loss Report', description: 'Generate P&L report for financial review.', category: 'reporting', priority: 'medium', actionLink: 'pl-report' },
    { title: 'Run Partner Capital Accounts', description: 'Allocate profit to partners and track capital balances.', category: 'reporting', priority: 'medium', actionLink: 'partner-capital' },
    { title: 'Run Personal Tax Return', description: 'Generate personal tax return form for partners.', category: 'reporting', priority: 'medium', actionLink: 'tax-return' },
    { title: 'Upload monthly transactions', description: 'Import recent bank statements to keep data current.', category: 'upload', priority: 'high', actionLink: 'upload' },
    { title: 'Categorize unidentified transactions', description: 'Review and categorize transactions for accurate reporting.', category: 'transactions', priority: 'medium', actionLink: 'transactions' },
    { title: 'Refine partially classified transactions', description: 'Improve categorization of partially classified items.', category: 'refinement', priority: 'medium', actionLink: 'refinement' },
    { title: 'Update Practice Profile', description: 'Review and update practice details in Admin Settings.', category: 'admin', priority: 'low', actionLink: 'practice-profile' },
    { title: 'Export files for Accountant', description: 'Prepare and export financial data for your accountant.', category: 'admin', priority: 'medium', actionLink: 'accountant-export' },
  ];

  const categoryColors = {
    reporting: { bg: '#EEF2FF', text: '#4F46E5' },
    transactions: { bg: '#FEF3C7', text: '#D97706' },
    refinement: { bg: '#FEE2E2', text: '#DC2626' },
    upload: { bg: '#DCFCE7', text: '#16A34A' },
    admin: { bg: '#F3E8FF', text: '#7C3AED' }
  };

  const statusColors = {
    pending: { bg: '#F3F4F6', text: '#6B7280' },
    in_progress: { bg: '#DBEAFE', text: COLORS.slainteBlue },
    completed: { bg: '#DCFCE7', text: COLORS.incomeColor }
  };

  return (
    <>
      {/* Main Modal - View All Tasks */}
      <div
        style={{
          position: 'fixed',
          inset: 0,
          zIndex: 50,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '1rem',
          backgroundColor: 'rgba(0, 0, 0, 0.5)'
        }}
      >
        <div
          style={{
            backgroundColor: COLORS.white,
            borderRadius: '0.75rem',
            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
            width: '100%',
            maxWidth: '48rem',
            maxHeight: '80vh',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
            border: `1px solid ${COLORS.lightGray}`
          }}
        >
          {/* Header */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '1rem',
              borderBottom: `1px solid ${COLORS.lightGray}`,
              flexShrink: 0
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
              <DollarSign className="h-5 w-5" style={{ color: COLORS.incomeColor }} />
              <h3 style={{ fontWeight: 600, color: COLORS.darkGray, margin: 0 }}>Financial Action Plan - All Tasks</h3>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <button
                onClick={() => {
                  setFinancialTaskForm({ title: '', description: '', category: 'reporting', priority: 'medium', assignedTo: '', dueDate: '' });
                  setShowAddFinancialTask(true);
                }}
                style={{
                  padding: '0.25rem 0.75rem',
                  fontSize: '0.875rem',
                  borderRadius: '0.5rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.25rem',
                  border: `1px solid ${COLORS.lightGray}`,
                  background: 'none',
                  color: COLORS.mediumGray,
                  cursor: 'pointer'
                }}
              >
                <Plus className="h-4 w-4" /> Add
              </button>
              <button
                onClick={onClose}
                style={{
                  padding: '0.25rem',
                  borderRadius: '0.375rem',
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer'
                }}
              >
                <X className="h-5 w-5" style={{ color: COLORS.mediumGray }} />
              </button>
            </div>
          </div>

          {/* Summary Stats */}
          <div
            style={{
              padding: '1rem',
              borderBottom: `1px solid ${COLORS.lightGray}`,
              backgroundColor: '#F9FAFB',
              flexShrink: 0
            }}
          >
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', textAlign: 'center' }}>
              <div>
                <p style={{ fontSize: '1.5rem', fontWeight: 700, color: COLORS.darkGray, margin: 0 }}>{allFinancialTasks.length}</p>
                <p style={{ fontSize: '0.75rem', color: COLORS.mediumGray, margin: 0 }}>Total</p>
              </div>
              <div>
                <p style={{ fontSize: '1.5rem', fontWeight: 700, color: '#6B7280', margin: 0 }}>{allFinancialTasks.filter(t => t.status === 'pending').length}</p>
                <p style={{ fontSize: '0.75rem', color: COLORS.mediumGray, margin: 0 }}>Pending</p>
              </div>
              <div>
                <p style={{ fontSize: '1.5rem', fontWeight: 700, color: COLORS.slainteBlue, margin: 0 }}>{allFinancialTasks.filter(t => t.status === 'in_progress').length}</p>
                <p style={{ fontSize: '0.75rem', color: COLORS.mediumGray, margin: 0 }}>In Progress</p>
              </div>
              <div>
                <p style={{ fontSize: '1.5rem', fontWeight: 700, color: COLORS.incomeColor, margin: 0 }}>{allFinancialTasks.filter(t => t.status === 'completed').length}</p>
                <p style={{ fontSize: '0.75rem', color: COLORS.mediumGray, margin: 0 }}>Completed</p>
              </div>
            </div>
          </div>

          {/* Task List - Scrollable */}
          <div
            style={{
              flex: 1,
              overflowY: 'auto',
              padding: '1rem',
              minHeight: 0
            }}
          >
            {allFinancialTasks.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '2rem 0', color: COLORS.mediumGray }}>
                <DollarSign style={{ height: '3rem', width: '3rem', margin: '0 auto 0.5rem', opacity: 0.3 }} />
                <p style={{ margin: 0 }}>No financial tasks yet</p>
                <p style={{ fontSize: '0.875rem', marginTop: '0.25rem' }}>Click "Add" to create your first task</p>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                {allFinancialTasks.map((task) => {
                  const isOverdue = task.status !== 'completed' && task.dueDate && new Date(task.dueDate) < new Date();
                  const colors = categoryColors[task.category] || categoryColors.reporting;
                  const sColors = statusColors[task.status] || statusColors.pending;
                  return (
                    <div
                      key={task.id}
                      style={{
                        padding: '0.75rem',
                        borderRadius: '0.5rem',
                        border: `1px solid ${isOverdue ? '#FCA5A5' : COLORS.lightGray}`,
                        backgroundColor: isOverdue ? '#FEF2F2' : COLORS.white,
                        opacity: task.status === 'completed' ? 0.6 : 1
                      }}
                    >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="px-2 py-0.5 text-xs rounded-full" style={{ backgroundColor: colors.bg, color: colors.text }}>
                            {task.category}
                          </span>
                          <span className="px-2 py-0.5 text-xs rounded-full" style={{ backgroundColor: sColors.bg, color: sColors.text }}>
                            {task.status.replace('_', ' ')}
                          </span>
                          {task.priority === 'high' && (
                            <span className="px-2 py-0.5 text-xs rounded-full bg-red-100 text-red-700">High</span>
                          )}
                          {isOverdue && (
                            <span className="px-2 py-0.5 text-xs rounded-full bg-red-100 text-red-700">Overdue</span>
                          )}
                        </div>
                        <p className={`font-medium mt-1 ${task.status === 'completed' ? 'line-through' : ''}`} style={{ color: COLORS.darkGray }}>{task.title}</p>
                        {task.description && (
                          <p className="text-sm mt-1" style={{ color: COLORS.mediumGray }}>{task.description}</p>
                        )}
                        <div className="flex items-center gap-3 mt-1 text-xs" style={{ color: COLORS.mediumGray }}>
                          {task.assignedTo && (
                            <span className="flex items-center gap-1">
                              <User className="h-3 w-3" /> {task.assignedTo}
                            </span>
                          )}
                          {task.dueDate && (
                            <span className="flex items-center gap-1">
                              <Calendar className="h-3 w-3" />
                              {new Date(task.dueDate).toLocaleDateString()}
                            </span>
                          )}
                          {task.completedDate && (
                            <span className="flex items-center gap-1">
                              <CheckCircle className="h-3 w-3" />
                              Done {new Date(task.completedDate).toLocaleDateString()}
                            </span>
                          )}
                        </div>
                      </div>
                      <div className="flex gap-1 ml-2">
                        <button
                          onClick={() => handleEditFinancialTask(task)}
                          className="p-1.5 rounded hover:bg-blue-100 transition-colors"
                          title="Edit task"
                        >
                          <Edit3 className="h-4 w-4" style={{ color: COLORS.slainteBlue }} />
                        </button>
                        {task.status !== 'completed' && (
                          <button
                            onClick={() => handleQuickStatusUpdate(task.id, 'completed')}
                            className="p-1.5 rounded hover:bg-green-100 transition-colors"
                            title="Mark as complete"
                          >
                            <CheckCircle className="h-4 w-4" style={{ color: '#059669' }} />
                          </button>
                        )}
                        <button
                          onClick={() => handleDeleteFinancialTask(task.id)}
                          className="p-1.5 rounded hover:bg-red-100 transition-colors"
                          title="Delete task"
                        >
                          <Trash2 className="h-4 w-4" style={{ color: COLORS.expenseColor }} />
                        </button>
                      </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Footer */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '1rem',
              borderTop: `1px solid ${COLORS.lightGray}`,
              flexShrink: 0
            }}
          >
            <p style={{ fontSize: '0.875rem', color: COLORS.mediumGray, margin: 0 }}>
              {allFinancialTasks.filter(t => t.status === 'completed').length} of {allFinancialTasks.length} tasks completed
            </p>
            <button
              onClick={onClose}
              style={{
                padding: '0.5rem 1rem',
                borderRadius: '0.5rem',
                fontSize: '0.875rem',
                fontWeight: 500,
                color: COLORS.white,
                backgroundColor: COLORS.slainteBlue,
                border: 'none',
                cursor: 'pointer'
              }}
            >
              Close
            </button>
          </div>
        </div>
      </div>

      {/* Edit Task Modal */}
      {editingFinancialTask && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            zIndex: 60,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '1rem',
            backgroundColor: 'rgba(0, 0, 0, 0.5)'
          }}
        >
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md" style={{ border: `1px solid ${COLORS.lightGray}` }}>
            <div className="flex items-center justify-between p-4 border-b" style={{ borderColor: COLORS.lightGray }}>
              <h3 className="font-semibold" style={{ color: COLORS.darkGray }}>Edit Task</h3>
              <button onClick={() => setEditingFinancialTask(null)} className="p-1 rounded hover:bg-gray-100">
                <X className="h-5 w-5" style={{ color: COLORS.mediumGray }} />
              </button>
            </div>
            <div className="p-4 space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Title</label>
                <input
                  type="text"
                  value={financialTaskForm.title}
                  onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, title: e.target.value })}
                  className="w-full p-2 border rounded-lg"
                  style={{ borderColor: COLORS.lightGray }}
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Status</label>
                <select
                  value={financialTaskForm.status}
                  onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, status: e.target.value })}
                  className="w-full p-2 border rounded-lg"
                  style={{ borderColor: COLORS.lightGray }}
                >
                  <option value="pending">Pending</option>
                  <option value="in_progress">In Progress</option>
                  <option value="completed">Completed</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Assign To</label>
                <select
                  value={financialTaskForm.assignedTo}
                  onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, assignedTo: e.target.value })}
                  className="w-full p-2 border rounded-lg"
                  style={{ borderColor: COLORS.lightGray }}
                >
                  <option value="">Unassigned</option>
                  {getAssigneeList().map((person, idx) => (
                    <option key={idx} value={person.name}>{person.name} ({person.role})</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Due Date</label>
                <input
                  type="date"
                  value={financialTaskForm.dueDate}
                  onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, dueDate: e.target.value })}
                  className="w-full p-2 border rounded-lg"
                  style={{ borderColor: COLORS.lightGray }}
                />
              </div>
            </div>
            <div className="flex justify-between p-4 border-t" style={{ borderColor: COLORS.lightGray }}>
              <button
                onClick={() => handleDeleteFinancialTask(editingFinancialTask.id)}
                className="px-4 py-2 text-sm rounded-lg text-red-600 hover:bg-red-50"
              >
                Delete
              </button>
              <div className="flex gap-2">
                <button
                  onClick={() => setEditingFinancialTask(null)}
                  className="px-4 py-2 text-sm rounded-lg border"
                  style={{ borderColor: COLORS.lightGray, color: COLORS.mediumGray }}
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveFinancialTaskEdit}
                  className="px-4 py-2 text-sm rounded-lg text-white"
                  style={{ backgroundColor: COLORS.slainteBlue }}
                >
                  Save Changes
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Add Financial Task Dialog */}
      {showAddFinancialTask && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            zIndex: 60,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '1rem',
            backgroundColor: 'rgba(0, 0, 0, 0.5)'
          }}
        >
          <div
            style={{
              backgroundColor: COLORS.white,
              borderRadius: '0.75rem',
              boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
              width: '100%',
              maxWidth: '32rem',
              maxHeight: '85vh',
              display: 'flex',
              flexDirection: 'column',
              border: `1px solid ${COLORS.lightGray}`
            }}
          >
            <div className="flex items-center justify-between p-4 border-b" style={{ borderColor: COLORS.lightGray }}>
              <h3 className="font-semibold" style={{ color: COLORS.darkGray }}>
                {showCustomTaskForm ? 'Create Custom Task' : 'Add Financial Task'}
              </h3>
              <button
                onClick={() => {
                  setShowAddFinancialTask(false);
                  setShowCustomTaskForm(false);
                }}
                className="p-1 rounded hover:bg-gray-100"
              >
                <X className="h-5 w-5" style={{ color: COLORS.mediumGray }} />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {!showCustomTaskForm ? (
                <>
                  {/* Quick Add - Preset Tasks */}
                  <div>
                    <label className="block text-sm font-medium mb-2" style={{ color: COLORS.darkGray }}>Select a task to add:</label>
                    <div className="grid grid-cols-1 gap-2">
                      {presetTasks.map((preset, idx) => (
                        <button
                          key={idx}
                          onClick={() => {
                            // Populate the form with preset values and show the edit form
                            setFinancialTaskForm({
                              title: preset.title,
                              description: preset.description || '',
                              category: preset.category || 'reporting',
                              priority: preset.priority || 'medium',
                              assignedTo: '',
                              dueDate: ''
                            });
                            setShowCustomTaskForm(true);
                          }}
                          className="flex items-center gap-3 p-3 rounded-lg border text-left hover:bg-gray-50 transition-colors"
                          style={{ borderColor: COLORS.lightGray }}
                        >
                          <div className="flex-1">
                            <p className="font-medium text-sm" style={{ color: COLORS.darkGray }}>{preset.title}</p>
                            <p className="text-xs mt-0.5" style={{ color: COLORS.mediumGray }}>{preset.description}</p>
                          </div>
                          <Plus className="h-4 w-4 flex-shrink-0" style={{ color: COLORS.slainteBlue }} />
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Create Custom Task Button */}
                  <button
                    onClick={() => setShowCustomTaskForm(true)}
                    className="w-full p-3 rounded-lg border-2 border-dashed text-center hover:bg-gray-50 transition-colors"
                    style={{ borderColor: COLORS.lightGray, color: COLORS.mediumGray }}
                  >
                    <Plus className="h-5 w-5 mx-auto mb-1" />
                    <span className="text-sm font-medium">Create Custom Task</span>
                  </button>
                </>
              ) : (
                <>
                  {/* Back button */}
                  <button
                    onClick={() => setShowCustomTaskForm(false)}
                    className="flex items-center gap-1 text-sm mb-2"
                    style={{ color: COLORS.slainteBlue }}
                  >
                    <ChevronRight className="h-4 w-4 rotate-180" />
                    Back to preset tasks
                  </button>

                  {/* Custom Task Form */}
                  <div>
                    <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Title *</label>
                    <input
                      type="text"
                      value={financialTaskForm.title}
                      onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, title: e.target.value })}
                      className="w-full p-2 border rounded-lg"
                      style={{ borderColor: COLORS.lightGray }}
                      placeholder="e.g., Quarterly tax review"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Description</label>
                    <textarea
                      value={financialTaskForm.description}
                      onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, description: e.target.value })}
                      className="w-full p-2 border rounded-lg"
                      style={{ borderColor: COLORS.lightGray }}
                      rows={2}
                      placeholder="Optional details..."
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Category</label>
                    <select
                      value={financialTaskForm.category}
                      onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, category: e.target.value })}
                      className="w-full p-2 border rounded-lg"
                      style={{ borderColor: COLORS.lightGray }}
                    >
                      <option value="reporting">Reporting (P&L, accounts)</option>
                      <option value="upload">Upload (transactions, data)</option>
                      <option value="transactions">Transactions (review)</option>
                      <option value="refinement">Refinement (categorization)</option>
                    </select>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Priority</label>
                      <select
                        value={financialTaskForm.priority}
                        onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, priority: e.target.value })}
                        className="w-full p-2 border rounded-lg"
                        style={{ borderColor: COLORS.lightGray }}
                      >
                        <option value="low">Low</option>
                        <option value="medium">Medium</option>
                        <option value="high">High</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Due Date</label>
                      <input
                        type="date"
                        value={financialTaskForm.dueDate}
                        onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, dueDate: e.target.value })}
                        className="w-full p-2 border rounded-lg"
                        style={{ borderColor: COLORS.lightGray }}
                      />
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-1" style={{ color: COLORS.darkGray }}>Assign To</label>
                    <select
                      value={financialTaskForm.assignedTo}
                      onChange={(e) => setFinancialTaskForm({ ...financialTaskForm, assignedTo: e.target.value })}
                      className="w-full p-2 border rounded-lg"
                      style={{ borderColor: COLORS.lightGray }}
                    >
                      <option value="">Unassigned</option>
                      {getAssigneeList().map((person, idx) => (
                        <option key={idx} value={person.name}>
                          {person.name} ({person.role})
                        </option>
                      ))}
                    </select>
                  </div>
                </>
              )}
            </div>
            {showCustomTaskForm && (
              <div className="flex justify-end gap-2 p-4 border-t" style={{ borderColor: COLORS.lightGray }}>
                <button
                  onClick={() => {
                    setShowAddFinancialTask(false);
                    setShowCustomTaskForm(false);
                  }}
                  className="px-4 py-2 text-sm rounded-lg border"
                  style={{ borderColor: COLORS.lightGray, color: COLORS.mediumGray }}
                >
                  Cancel
                </button>
                <button
                  onClick={() => {
                    handleAddFinancialTask();
                    setShowCustomTaskForm(false);
                  }}
                  disabled={!financialTaskForm.title}
                  className="px-4 py-2 text-sm rounded-lg text-white disabled:opacity-50"
                  style={{ backgroundColor: COLORS.slainteBlue }}
                >
                  Add Task
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Confirmation Dialogs */}
      <ConfirmDialog
        isOpen={confirmDialog.isOpen && confirmDialog.type === 'complete'}
        onConfirm={handleConfirmComplete}
        onCancel={handleCancelDialog}
        title="Confirm Completion"
        message="Are you sure you want to mark this task as complete?"
        confirmText="Complete"
        confirmStyle="primary"
      />

      <ConfirmDialog
        isOpen={confirmDialog.isOpen && confirmDialog.type === 'delete'}
        onConfirm={handleConfirmDelete}
        onCancel={handleCancelDialog}
        title="Confirm Delete"
        message="Are you sure you want to delete this task? This action cannot be undone."
        confirmText="Delete"
        confirmStyle="danger"
      />
    </>
  );
};

export default FinancialTasksModal;
