/**
 * Task Utilities
 * Normalizers and helpers for unifying GMS Action Items and Financial Tasks
 */
import COLORS from '../utils/colors';

/**
 * Normalize a GMS Action Item to unified task format
 * @param {Object} action - GMS action item from practiceProfileStorage
 * @returns {Object} Normalized task object
 */
export function normalizeActionItem(action) {
  return {
    id: action.id,
    type: 'gms',
    title: action.title,
    description: action.description || '',
    category: action.category || 'uncategorized',
    status: action.status || 'pending',
    assignedTo: action.assignedTo || null,
    dueDate: action.dueDate || null,
    createdDate: action.createdDate || null,
    completedDate: action.completedDate || null,
    priority: action.type === 'priority' ? 'high' : 'medium',
    potentialValue: action.potentialValue || 0,
    effort: action.effort || 'medium',
    showOnDashboard: action.showOnDashboard !== false,
    notes: action.notes || '',
    actionLink: action.actionLink || null,
    // Keep original data for updates
    _source: 'gms',
    _originalId: action.id,
    _recommendationId: action.recommendationId
  };
}

/**
 * Normalize a Financial Task to unified task format
 * @param {Object} task - Financial task from practiceProfileStorage
 * @returns {Object} Normalized task object
 */
export function normalizeFinancialTask(task) {
  return {
    id: task.id,
    type: 'financial',
    title: task.title,
    description: task.description || '',
    category: task.category || 'general',
    status: task.status || 'pending',
    assignedTo: task.assignedTo || null,
    dueDate: task.dueDate || null,
    createdDate: task.createdDate || null,
    completedDate: task.completedDate || null,
    priority: task.priority || 'medium',
    potentialValue: 0, // Financial tasks don't have potential value
    effort: 'medium',
    showOnDashboard: true,
    notes: task.notes || '',
    actionLink: task.actionLink || null,
    autoGenerated: task.autoGenerated || false,
    // Keep original data for updates
    _source: 'financial',
    _originalId: task.id
  };
}

/**
 * Normalize all tasks from both sources
 * @param {Array} actionItems - GMS action items
 * @param {Array} financialTasks - Financial tasks
 * @returns {Array} Combined and normalized tasks
 */
export function normalizeAllTasks(actionItems, financialTasks) {
  const normalizedGMS = (actionItems || []).map(normalizeActionItem);
  const normalizedFinancial = (financialTasks || []).map(normalizeFinancialTask);
  return [...normalizedGMS, ...normalizedFinancial];
}

/**
 * Check if a task is overdue
 * @param {Object} task - Normalized task object
 * @returns {boolean} True if task is overdue
 */
export function isTaskOverdue(task) {
  if (!task.dueDate || task.status === 'completed') return false;
  return new Date(task.dueDate) < new Date();
}

/**
 * Check if a task is due soon (within 7 days)
 * @param {Object} task - Normalized task object
 * @returns {boolean} True if task is due soon
 */
export function isTaskDueSoon(task) {
  if (!task.dueDate || task.status === 'completed') return false;
  const now = new Date();
  const dueDate = new Date(task.dueDate);
  const weekFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  return dueDate >= now && dueDate <= weekFromNow;
}

/**
 * Sort tasks by priority and due date
 * @param {Array} tasks - Array of normalized tasks
 * @returns {Array} Sorted tasks
 */
export function sortTasks(tasks) {
  const priorityOrder = { high: 0, medium: 1, low: 2 };

  return [...tasks].sort((a, b) => {
    // Overdue tasks first
    const aOverdue = isTaskOverdue(a);
    const bOverdue = isTaskOverdue(b);
    if (aOverdue && !bOverdue) return -1;
    if (!aOverdue && bOverdue) return 1;

    // Then by priority
    if (priorityOrder[a.priority] !== priorityOrder[b.priority]) {
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    }

    // Then by due date
    if (a.dueDate && b.dueDate) {
      return new Date(a.dueDate) - new Date(b.dueDate);
    }
    if (a.dueDate && !b.dueDate) return -1;
    if (!a.dueDate && b.dueDate) return 1;

    return 0;
  });
}

/**
 * Filter tasks by type
 * @param {Array} tasks - Array of normalized tasks
 * @param {string} type - 'gms', 'financial', or 'all'
 * @returns {Array} Filtered tasks
 */
export function filterTasksByType(tasks, type) {
  if (type === 'all') return tasks;
  return tasks.filter(task => task.type === type);
}

/**
 * Filter tasks by status
 * @param {Array} tasks - Array of normalized tasks
 * @param {string} status - 'pending', 'in_progress', 'completed', or 'active' (pending + in_progress)
 * @returns {Array} Filtered tasks
 */
export function filterTasksByStatus(tasks, status) {
  if (status === 'active') {
    return tasks.filter(task => task.status !== 'completed');
  }
  return tasks.filter(task => task.status === status);
}

/**
 * Get task statistics
 * @param {Array} tasks - Array of normalized tasks
 * @returns {Object} Task statistics
 */
export function getTaskStats(tasks) {
  const stats = {
    total: tasks.length,
    pending: 0,
    inProgress: 0,
    completed: 0,
    overdue: 0,
    dueSoon: 0,
    totalPotentialValue: 0,
    gmsCount: 0,
    financialCount: 0
  };

  tasks.forEach(task => {
    if (task.status === 'pending') stats.pending++;
    if (task.status === 'in_progress') stats.inProgress++;
    if (task.status === 'completed') stats.completed++;
    if (isTaskOverdue(task)) stats.overdue++;
    if (isTaskDueSoon(task)) stats.dueSoon++;
    if (task.potentialValue) stats.totalPotentialValue += task.potentialValue;
    if (task.type === 'gms') stats.gmsCount++;
    if (task.type === 'financial') stats.financialCount++;
  });

  return stats;
}

/**
 * Format currency for display
 * @param {number} value - Currency value
 * @returns {string} Formatted currency string
 */
export function formatCurrency(value) {
  return new Intl.NumberFormat('en-IE', {
    style: 'currency',
    currency: 'EUR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(value || 0);
}

/**
 * Format date for display
 * @param {string|Date} date - Date to format
 * @returns {string} Formatted date string
 */
export function formatDate(date) {
  if (!date) return '';
  return new Date(date).toLocaleDateString('en-IE', {
    day: 'numeric',
    month: 'short',
    year: 'numeric'
  });
}

/**
 * Get priority color
 * @param {string} priority - Task priority
 * @returns {Object} Color object with bg and text properties
 */
export function getPriorityColor(priority) {
  const colors = {
    high: { bg: COLORS.errorLight, text: COLORS.error, border: COLORS.errorLight },
    medium: { bg: COLORS.warningLight, text: COLORS.warningDark, border: COLORS.warningLight },
    low: { bg: COLORS.successLighter, text: COLORS.success, border: COLORS.successLighter }
  };
  return colors[priority] || colors.medium;
}

/**
 * Get status color
 * @param {string} status - Task status
 * @returns {Object} Color object with bg and text properties
 */
export function getStatusColor(status) {
  const colors = {
    pending: { bg: COLORS.bgHover, text: COLORS.textMuted, border: COLORS.borderLight },
    in_progress: { bg: COLORS.infoLighter, text: COLORS.slainteBlue, border: COLORS.infoLighter },
    completed: { bg: COLORS.successLighter, text: COLORS.success, border: COLORS.successLighter }
  };
  return colors[status] || colors.pending;
}

/**
 * Get category color for task type badges
 * @param {string} type - Task type ('gms' or 'financial')
 * @returns {Object} Color object
 */
export function getTypeColor(type) {
  const colors = {
    gms: { bg: COLORS.slainteBlueLight, text: COLORS.accentPurple, border: COLORS.infoLighter },
    financial: { bg: COLORS.accentPurpleLight, text: COLORS.chartViolet, border: COLORS.accentPurpleLight }
  };
  return colors[type] || colors.financial;
}
