import React, { createContext, useState, useEffect, useContext, useCallback } from 'react';
import {
  get as getProfile,
  getActionItems,
  getFinancialTasks,
  updateActionItem,
  updateFinancialTask,
  deleteActionItem,
  deleteFinancialTask,
  addActionItem,
  addFinancialTask,
  createFinancialTask as createFinancialTaskRecord
} from '../storage/practiceProfileStorage';
import {
  normalizeAllTasks,
  sortTasks,
  filterTasksByStatus,
  getTaskStats,
  isTaskOverdue
} from '../utils/taskUtils';
import { useAppContext } from './AppContext';
import { shouldRecommendRefinement, getRefinementCategoryCounts } from '../utils/categoryRefinementUtils';

// Create the context
const TasksContext = createContext(null);

export const TasksProvider = ({ children }) => {
  // Get transaction data from AppContext for auto-generation
  const { transactions, unidentifiedTransactions, paymentAnalysisData } = useAppContext();

  // Widget UI state
  const [isOpen, setIsOpen] = useState(false);

  // Collapsible sections state - collapsed by default for cleaner appearance
  const [gmsExpanded, setGmsExpanded] = useState(false);
  const [financialExpanded, setFinancialExpanded] = useState(false);

  // Highlighted task (for cross-component navigation from Health Check donut)
  const [highlightedTaskId, setHighlightedTaskId] = useState(null);

  // Tasks data
  const [tasks, setTasks] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  // Load tasks from storage
  const loadTasks = useCallback(() => {
    try {
      const actionItems = getActionItems();
      const financialTasks = getFinancialTasks();
      const allTasks = normalizeAllTasks(actionItems, financialTasks);
      setTasks(allTasks);
    } catch (error) {
      console.error('Error loading tasks:', error);
      setTasks([]);
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Initial load
  useEffect(() => {
    loadTasks();
  }, [loadTasks]);

  // Listen for external task refresh events (e.g. from NewGMSHealthCheck AreaTaskPanel)
  useEffect(() => {
    const handleRefresh = () => loadTasks();
    window.addEventListener('tasks:refresh', handleRefresh);
    return () => window.removeEventListener('tasks:refresh', handleRefresh);
  }, [loadTasks]);

  // Listen for "open widget and highlight a specific task" events (from Health Check donut)
  useEffect(() => {
    const handleOpenAndHighlight = (e) => {
      const taskId = e.detail?.taskId;
      const expandSection = e.detail?.expandSection;
      setIsOpen(true);
      // Expand the relevant section (default to GMS for backwards compatibility)
      if (expandSection === 'financial') {
        setFinancialExpanded(true);
      } else if (expandSection === 'gms') {
        setGmsExpanded(true);
      } else {
        setGmsExpanded(true);
      }
      if (taskId) {
        setHighlightedTaskId(taskId);
        // Clear highlight after 2 seconds
        setTimeout(() => setHighlightedTaskId(null), 2000);
      }
    };
    window.addEventListener('tasks:openAndHighlight', handleOpenAndHighlight);
    return () => window.removeEventListener('tasks:openAndHighlight', handleOpenAndHighlight);
  }, []);

  // Auto-generate financial tasks based on system status
  useEffect(() => {
    const generateAutoTasks = () => {
      const now = new Date();
      const currentYear = now.getFullYear();
      const currentMonth = now.getMonth(); // 0-11

      // 1. STALE DATA CHECK - If no transactions in over 30 days, suggest upload
      if (transactions && transactions.length > 0) {
        const latestTxDate = transactions.reduce((latest, t) => {
          if (!t.date) return latest;
          const tDate = new Date(t.date);
          return !latest || tDate > latest ? tDate : latest;
        }, null);

        if (latestTxDate) {
          const daysSinceLatest = Math.floor((now - latestTxDate) / (1000 * 60 * 60 * 24));
          if (daysSinceLatest > 30) {
            const task = createFinancialTaskRecord({
              title: 'Upload monthly transactions',
              description: `Last transaction was ${daysSinceLatest} days ago. Upload recent bank statements to keep data current.`,
              category: 'upload',
              priority: 'high',
              autoGenerated: true,
              actionLink: 'upload'
            });
            addFinancialTask(task);
          }
        }
      }

      // 2. UNGROUPED TRANSACTIONS - Suggest group assignment (Pass 1)
      if (unidentifiedTransactions && unidentifiedTransactions.length > 0) {
        // Check how many lack a group vs lack a category
        const ungrouped = unidentifiedTransactions.filter(t => !t.suggestedGroup || !t.groupConfirmed);
        const groupedButUncategorised = unidentifiedTransactions.filter(t => t.groupConfirmed && !t.categoryCode);

        if (ungrouped.length > 0) {
          const task = createFinancialTaskRecord({
            title: 'Assign groups to unidentified transactions',
            description: `${ungrouped.length} transaction${ungrouped.length !== 1 ? 's' : ''} need a group assignment for your dashboard and financial overview.`,
            category: 'transactions',
            priority: ungrouped.length > 20 ? 'high' : 'medium',
            autoGenerated: true,
            actionLink: 'transactions'
          });
          addFinancialTask(task);
        }

        // Pass 2 reminder: grouped but uncategorised
        if (groupedButUncategorised.length > 0) {
          const task = createFinancialTaskRecord({
            title: 'Assign detailed categories to grouped transactions',
            description: `${groupedButUncategorised.length} transaction${groupedButUncategorised.length !== 1 ? 's' : ''} have groups but need specific categories for detailed reports like P&L.`,
            category: 'transactions',
            priority: 'medium',
            autoGenerated: true,
            actionLink: 'transactions'
          });
          addFinancialTask(task);
        }
      }

      // 3. PARTIALLY CLASSIFIED - Suggest refinement if there are partial classifications
      if (transactions && transactions.length > 0) {
        const refCheck = shouldRecommendRefinement(transactions);
        const refCounts = getRefinementCategoryCounts(transactions);
        if (refCheck.shouldShow) {
          const task = createFinancialTaskRecord({
            title: 'Refine partially classified transactions',
            description: refCounts.essential > 0
              ? `${refCounts.essential} essential transactions need refinement for accurate reporting.`
              : `${refCheck.count} transactions can be better categorized.`,
            category: 'refinement',
            priority: refCounts.essential > 0 ? 'high' : 'medium',
            autoGenerated: true,
            actionLink: 'refinement'
          });
          addFinancialTask(task);
        }
      }

      // 4. PRIOR YEAR P&L REPORT - In Jan-March, suggest generating prior year P&L
      const shouldGeneratePriorYear = currentMonth < 3; // Jan-March
      if (shouldGeneratePriorYear && transactions && transactions.length > 0) {
        const reportYear = currentYear - 1;
        const hasDataForYear = transactions.some(t => {
          if (!t.date) return false;
          return new Date(t.date).getFullYear() === reportYear;
        });

        if (hasDataForYear) {
          const task = createFinancialTaskRecord({
            title: `Generate ${reportYear} Annual P&L Report`,
            description: `Create your annual Profit & Loss report for ${reportYear} tax filing and financial review.`,
            category: 'reporting',
            priority: 'high',
            autoGenerated: true,
            actionLink: 'export'
          });
          addFinancialTask(task);
        }
      }

      // 5. MONTHLY P&L REMINDER - First week of each month
      if (now.getDate() <= 7) {
        const previousMonth = new Date(currentYear, currentMonth - 1, 1);
        const prevMonthName = previousMonth.toLocaleString('default', { month: 'long' });
        const task = createFinancialTaskRecord({
          title: `Run ${prevMonthName} Profit & Loss Report`,
          description: 'Review monthly financial performance and compare to previous periods.',
          category: 'reporting',
          priority: 'medium',
          autoGenerated: true,
          actionLink: 'export'
        });
        addFinancialTask(task);
      }

      // 6. GMS HEALTH CHECK - Once 12+ months of GMS data uploaded and health check not yet run
      if (paymentAnalysisData && paymentAnalysisData.length > 0) {
        const uniqueGMSMonths = new Set(paymentAnalysisData.map(d => `${d.month}-${d.year}`)).size;
        const profile = getProfile();
        const healthCheckDone = profile?.healthCheckData?.healthCheckComplete === true;

        if (uniqueGMSMonths >= 12 && !healthCheckDone) {
          const existingActions = getActionItems();
          if (!existingActions.some(a => a.id?.startsWith('task-gms-healthcheck') && a.status !== 'completed')) {
            addActionItem({
              id: `task-gms-healthcheck-${Date.now()}`,
              title: 'Run GMS Health Check',
              description: `You have ${uniqueGMSMonths} months of GMS data uploaded. Run the Health Check to identify unclaimed income, leave entitlements, and panel trends.`,
              category: 'analysis',
              type: 'priority',
              status: 'pending',
              actionLink: 'gms-health-check',
              showOnDashboard: true,
              createdDate: new Date().toISOString()
            });
          }
        }
      }

      // Reload tasks after generating
      loadTasks();
    };

    // Only run if we have transaction data loaded
    if (transactions !== undefined) {
      generateAutoTasks();
    }
  }, [transactions?.length, unidentifiedTransactions?.length, paymentAnalysisData?.length, loadTasks]);

  // Refresh tasks (call this after external changes)
  const refreshTasks = useCallback(() => {
    loadTasks();
  }, [loadTasks]);

  // Get active (non-completed) tasks
  const getActiveTasks = useCallback(() => {
    return sortTasks(filterTasksByStatus(tasks, 'active'));
  }, [tasks]);

  // Get GMS tasks only
  const getGMSTasks = useCallback(() => {
    return sortTasks(tasks.filter(t => t.type === 'gms' && t.status !== 'completed'));
  }, [tasks]);

  // Get Financial tasks only
  const getFinancialTasksList = useCallback(() => {
    return sortTasks(tasks.filter(t => t.type === 'financial' && t.status !== 'completed'));
  }, [tasks]);

  // Get overdue tasks
  const getOverdueTasks = useCallback(() => {
    return sortTasks(tasks.filter(isTaskOverdue));
  }, [tasks]);

  // Get task statistics
  const stats = getTaskStats(tasks);

  // Update a task
  const updateTask = useCallback((taskId, updates) => {
    // Find the task to determine which storage to update
    const task = tasks.find(t => t.id === taskId);
    if (!task) {
      console.error('Task not found:', taskId);
      return false;
    }

    let success = false;
    if (task._source === 'gms') {
      success = updateActionItem(taskId, updates);
    } else if (task._source === 'financial') {
      success = updateFinancialTask(taskId, updates);
    }

    if (success) {
      // Reload tasks to get updated data
      loadTasks();
    }

    return success;
  }, [tasks, loadTasks]);

  // Delete a task
  const deleteTask = useCallback((taskId) => {
    const task = tasks.find(t => t.id === taskId);
    if (!task) {
      console.error('Task not found:', taskId);
      return false;
    }

    let success = false;
    if (task._source === 'gms') {
      success = deleteActionItem(taskId);
    } else if (task._source === 'financial') {
      success = deleteFinancialTask(taskId);
    }

    if (success) {
      loadTasks();
    }

    return success;
  }, [tasks, loadTasks]);

  // Complete a task and notify other components (e.g. Health Check donut)
  const completeTask = useCallback((taskId) => {
    const result = updateTask(taskId, { status: 'completed' });
    if (result) {
      window.dispatchEvent(new Event('tasks:refresh'));
    }
    return result;
  }, [updateTask]);

  // Start a task (set to in_progress)
  const startTask = useCallback((taskId) => {
    return updateTask(taskId, { status: 'in_progress' });
  }, [updateTask]);

  // Create a new GMS task
  const createGMSTask = useCallback((taskData) => {
    const newTask = {
      id: `action-${Date.now()}`,
      title: taskData.title,
      description: taskData.description || '',
      category: taskData.category || 'manual',
      type: taskData.priority === 'high' ? 'priority' : 'growth',
      status: 'pending',
      assignedTo: taskData.assignedTo || null,
      dueDate: taskData.dueDate || null,
      potentialValue: taskData.potentialValue || 0,
      effort: taskData.effort || 'medium',
      showOnDashboard: true,
      createdDate: new Date().toISOString(),
      notes: taskData.notes || ''
    };

    const success = addActionItem(newTask);
    if (success) {
      loadTasks();
    }
    return success;
  }, [loadTasks]);

  // Create a new Financial task
  const createFinancialTask = useCallback((taskData) => {
    const newTask = {
      id: `fin-task-${Date.now()}`,
      title: taskData.title,
      description: taskData.description || '',
      category: taskData.category || 'general',
      priority: taskData.priority || 'medium',
      status: 'pending',
      assignedTo: taskData.assignedTo || null,
      dueDate: taskData.dueDate || null,
      actionLink: taskData.actionLink || null,
      autoGenerated: false,
      createdDate: new Date().toISOString(),
      notes: taskData.notes || ''
    };

    const success = addFinancialTask(newTask);
    if (success) {
      loadTasks();
    }
    return success;
  }, [loadTasks]);

  // Widget controls
  const openWidget = useCallback(() => setIsOpen(true), []);
  const closeWidget = useCallback(() => setIsOpen(false), []);
  const toggleWidget = useCallback(() => setIsOpen(prev => !prev), []);

  // Section controls
  const toggleGmsSection = useCallback(() => setGmsExpanded(prev => !prev), []);
  const toggleFinancialSection = useCallback(() => setFinancialExpanded(prev => !prev), []);

  // Context value
  const value = {
    // Widget state
    isOpen,
    openWidget,
    closeWidget,
    toggleWidget,

    // Section state
    gmsExpanded,
    financialExpanded,
    toggleGmsSection,
    toggleFinancialSection,

    // Tasks data
    tasks,
    isLoading,
    stats,
    highlightedTaskId,

    // Filtered task getters
    getActiveTasks,
    getGMSTasks,
    getFinancialTasksList,
    getOverdueTasks,

    // Task actions
    updateTask,
    deleteTask,
    completeTask,
    startTask,
    createGMSTask,
    createFinancialTask,
    refreshTasks
  };

  return (
    <TasksContext.Provider value={value}>
      {children}
    </TasksContext.Provider>
  );
};

// Custom hook for consuming the context
export const useTasks = () => {
  const context = useContext(TasksContext);
  if (!context) {
    throw new Error('useTasks must be used within a TasksProvider');
  }
  return context;
};

export default TasksContext;
